CREATE TABLE Libro
(
Id VARCHAR(32) DEFAULT sys_guid() PRIMARY KEY NOT NULL,
Titulo VARCHAR(100) UNIQUE NOT NULL,
Año INT DEFAULT 0 NOT NULL,
Genero VARCHAR(32) NOT NULL,
NumeroPaginas INT DEFAULT 0 NOT NULL,
Autor VARCHAR(32) NOT NULL,
FOREIGN KEY(Genero) REFERENCES Genero(Id),
FOREIGN KEY(Autor) REFERENCES Autor(Id)
)