//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO
    {
        public string ID { get; set; }
        public string TITULO { get; set; }
        public decimal AÑO { get; set; }
        public string GENERO { get; set; }
        public decimal NUMEROPAGINAS { get; set; }
        public string AUTOR { get; set; }
    
        public virtual AUTOR AUTOR1 { get; set; }
        public virtual GENERO GENERO1 { get; set; }
    }
}
